### ISSUE TITLE
Silent installation switches

### ISSUE THREAD

**Issue by kamiloxf** [Wilenty/VisualC-redist-installers-Demos#1]
Please add silent install switches to Defender Switcher

**Comment by Wilenty** [comment]
Hello,
for first what is a connection between the VC++ installers and the Switcher?

I won't add the silent switches that this small program will not be detected as a dangerous (virus, malware, etc.)

Please take in mind that the AV checks all hidden programs even more, so, it's easy way to get "banned".

**Comment by kamiloxf** [comment]
I wrote here because I didn't know how to contact you


and I would like to know one thing non-public.

**Comment by kamiloxf** [comment]
How can I contact you? Because I want to ask about something that shouldn't appear on github

**Comment by Wilenty** [comment]
You can contact with me private on
MDL: https://forums.mydigitallife.net/members/wilenty.411805/
G3D: https://forums.guru3d.com/members/wilenty.273654/

I also have my own Discord, but it's not visible publicly - I can say it's only for friends :)
