### ISSUE TITLE
Basic Runtime Libraries [HC] by Wilenty 2019-03-25_2 has become the best historical singing.

### ISSUE THREAD

**Issue by ednykissyou** [Wilenty/VisualC-redist-installers-Demos#2]
新版太难用，Basic Runtime Libraries [HC] by Wilenty 2019-03-25_2已成绝唱。
新版似乎只是个演示，没有起到作用，未能卸载，也未能安装。界面也很小。
Basic Runtime Libraries [HC] by Wilenty 2019-03-25_2已成绝唱。

The new version is too difficult to use.Basic Runtime Libraries [HC] by Wilenty 2019-03-25_2 has become the best historical singing.
The new version seems to be just a demonstration. It has not played a role, failed to uninstall, nor was it installed. The interface is also very small.
Basic Runtime Libraries [HC] By Wilenty 2019-03-25_2 has become a singing.

**Comment by Wilenty** [comment]
Hello @ednykissyou,
thanks for your comment.

But, I had to use other translator to understand what you meant:
https://www.deepl.com/en/translator#zh/en/%E6%96%B0%E7%89%88%E5%A4%AA%E9%9A%BE%E7%94%A8%EF%BC%8CBasic%20Runtime%20Libraries%20%5BHC%5D%20by%20Wilenty%202019-03-25_2%E5%B7%B2%E6%88%90%E7%BB%9D%E5%94%B1%E3%80%82%0A%E6%96%B0%E7%89%88%E4%BC%BC%E4%B9%8E%E5%8F%AA%E6%98%AF%E4%B8%AA%E6%BC%94%E7%A4%BA%EF%BC%8C%E6%B2%A1%E6%9C%89%E8%B5%B7%E5%88%B0%E4%BD%9C%E7%94%A8%EF%BC%8C%E6%9C%AA%E8%83%BD%E5%8D%B8%E8%BD%BD%EF%BC%8C%E4%B9%9F%E6%9C%AA%E8%83%BD%E5%AE%89%E8%A3%85%E3%80%82%E7%95%8C%E9%9D%A2%E4%B9%9F%E5%BE%88%E5%B0%8F%E3%80%82%0ABasic%20Runtime%20Libraries%20%5BHC%5D%20by%20Wilenty%202019-03-25_2%E5%B7%B2%E6%88%90%E7%BB%9D%E5%94%B1%E3%80%82
```
New version is too hard to use, Basic Runtime Libraries [HC] by Wilenty 2019-03-25_2 has become extinct.
The new version seems to be just a demo that doesn't work, failed to uninstall and failed to install. The interface is also very small.
Basic Runtime Libraries [HC] by Wilenty 2019-03-25_2 has become extinct.
```

> (...) The interface is also very small.

Starting from the beginning of the program...
Did you saw the blinking (light green) text with information about possibility to make the text bigger or smaller? It not I will show you it in the red frame:
<img width="406" alt="First01" src="https://github.com/Wilenty/VisualC-redist-installers-Demos/assets/61757638/83376d05-e0f3-4375-855f-3f38adc3d162">

> New version is too hard to use(...)

probably in the DEMO version.
Anyway, if the graphical interface is too hard to use, you have the *.cmd script with command-line explanation. Full explanation of the command line parameters available under the "Menu" button and then the "Parameters?" button:
![Basic01](https://github.com/Wilenty/VisualC-redist-installers-Demos/assets/61757638/e36f18c0-b0a9-47cf-bd2e-4f0158c82b73)
![Types02](https://github.com/Wilenty/VisualC-redist-installers-Demos/assets/61757638/00bdbee7-1422-4f5f-b066-e5c8068f02b8)
![Components04](https://github.com/Wilenty/VisualC-redist-installers-Demos/assets/61757638/c95c7b4e-d6eb-4840-98d1-0ed0d3350a0d)

> The new version seems to be just a demo that doesn't work, failed to uninstall and failed to install.(...)

I did a VC++ runtimes update on my test W10 on VM (virtual machine), but I hid personal information.
First launch/execution (uninstall):
![FirstRound03](https://github.com/Wilenty/VisualC-redist-installers-Demos/assets/61757638/938c7cda-f8f1-497e-85cb-ce13ca42586b)
![FirstRound04](https://github.com/Wilenty/VisualC-redist-installers-Demos/assets/61757638/db49aa8d-b500-481c-ab56-6702aaf4578f)
![FirstRound05](https://github.com/Wilenty/VisualC-redist-installers-Demos/assets/61757638/ccf174cb-b7d3-4268-8587-2f1fa7e1c559)


Second launch/execution (install):
![SecondRound06](https://github.com/Wilenty/VisualC-redist-installers-Demos/assets/61757638/1e49cc3e-15cf-4940-af0e-ea4bcf329c1f)
**What "failed to uninstall and failed to install"?**

If you want the full version without external VC_redist.\*.exe support, please support me for $10 on Patreon or 10€ on ko-fi. But if you want the version with external VC_redist.\*.exe support, please support me for $100 on Patreon or 100€ on ko-fi.

Greetings,
Wilenty

**Comment by Wilenty** [comment]
**Wait, why you opened new issue in the new repository? It's some game or what?
If you want seriously talk (write) with me, please don't open any other issues in other repositories.**

![image](https://github.com/Wilenty/VisualC-redist-installers-Demos/assets/61757638/122ac8f0-99c8-4202-aeef-7b226a5f07e3)

At the outset. Please don't think that "I want to cry on your neck". You asking - I'm answering.

> Great God, the people call for your glory to return.

I'm not going to become a saint. I just need "other people resources" to still be here.

> I think your Basic Runtime Libraries [HC] by Wilenty 2019-03-25_2 is really great.

Thanks! I know it, some other people (who still uses it) also know it. I have spend a loot of the time to make it as it is.

> I didn't know why it stopped.
The 2022 version does not seem to be available. It's a pity.

Sorry to say, but "stroking me on the back" it's nice, but not enough for me to survive on this planet. When my programs was for free, people don't willing to support me. So I had to make tough decision to share my programs for support (donation). The people can get their own (private/corporate) version after amount of donation will appear on my account.

> Can users customize the VC version?

Of course, but I changed the "choice window" to "choice page" of VC++ selection:

![ChoicePage01](https://github.com/Wilenty/VisualC-redist-installers-Demos/assets/61757638/2e71e102-3a90-410b-891c-298bf3fd619e)
![ChoicePage02](https://github.com/Wilenty/VisualC-redist-installers-Demos/assets/61757638/becfa745-afe3-45ac-84ce-e4a08320fbb6)

Now you don't have to restart the program to change the VC++ version of 2015, 2017, 2019 and 2022.

The new version (after 2019-03-25) supports all parameters from command-line, same as you can do it via graphical interface. Also the new version should support ARM64 OS, but I don't have computer with ARM64 CPU to deeply check it...

Greetings,
Wilenty
